FROM node:22-alpine

RUN apk add --no-cache openssl libc6-compat bash

WORKDIR /app

RUN addgroup -S app && adduser -S app -G app \
    && chown -R app:app /app

USER app

COPY --chown=app:app package*.json ./
COPY --chown=app:app prisma ./prisma

RUN npm install

COPY --chown=app:app . .

EXPOSE 3000

CMD ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && npm run start:dev"]
